# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://jackwcollins.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Jack Collins"
description: CTO @ Gondola

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Jack Collins
author-bio: Co-founder and CTO @ Gondola
author-image: headshot.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/JackWCollins
linkedin: https://www.linkedin.com/in/jackwcollins/
medium: false
google-scholar: false
email: hello@jackcollins.io

# footer information
footer-msg: "Jack Collins"
footer-msg-link: https://www.linkedin.com/in/jackwcollins/

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
